---
 
- name: "update apt packages."
  apt:
    update_cache: yes
    
# - name: "upgrade packages."
#   become: true
#   apt:
#     upgrade: "yes"
    
- name: "install python for Ansible."
  become: true
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
  changed_when: false
    
- name: "Install zip utility."
  apt:
    name: [ "zip", "unzip" ]
    state: latest
#    update_cache: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
#    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash - && sudo apt-get install -y nodejs

# - name: remove dependencies that are no longer required
#   apt:
#     autoremove: yes



