---
# - name: "Creates backend app directory"
#   file:
#     path: ~/backend_app
#     state: directory

# - name: "Copy compiled backend app"
#   copy:
#     src: dist.zip
#     dest: "~/backend_app/dist.zip"

# - name: "Unzip backend files to correct directory"
#   shell: |
#     cd ~/backend_app
#     unzip dist.zip
#     rm -rf dist.zip

# - name: "Install dependencies for project"
#   shell: |
#     cd ~/backend_app
#     npm install

# - name: "Executing node"
#   shell: |
#     export
#     cd ~/backend_app
#     pm2 start main.js
#   register: execute_node

# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2 to start as service"
#   shell: |
#     env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu

- name: "unarchive backend files"
  unarchive:
    src: artifact-backend.tar.gz
    dest: /home/ubuntu/
    
- name: "executing node"
  shell: |
    cd /home/ubuntu/root/project/backend
    pm2 stop default
    sudo pm2 start npm --name udapeople -- start
    pm2 ls

# - name: "executing node"
#   shell: |
#     cd /home/ubuntu/backend
# #    pm2 stop default
# #    pm2 start npm --name 'udapeople' -- start
# #    pm2 ls
#     sudo npm install
#     sudo npm run build
#     sudo pm2 start npm --name backend -- start
# #######
#    sudo npm install
#    sudo npm run build
