version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "hello_app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops-capstone  # TODO: Include in cache the "bin" directory
          key: v1-dependencies-{{ checksum "hello_app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops-capstone/bin/activate
            make lint 
      - run:
          name: Run build docker
          command: |
            source .devops-capstone/bin/activate
            make build-docker
      - run:
          name: Run upload docker
          command: |
            source .devops-capstone/bin/activate
            make upload-docker

  # build-docker:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build Docker Image
  #         command: |
  #           ./bin/build_docker.sh

  # docker-upload:
  #   docker:
  #     - image: circleci/python:3.7.3-stretch
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: Upload Docker image
  #         command: |
  #           source .devops-capstone/bin/activate
  #           make push-docker

workflows:
  default:
    jobs:
      - init        
      # - build-docker:
      #     requires: [init]
      # - docker-upload:
      #     requires: [build-docker]
      # - docker/publish:
      #     matrix:
      #       parameters:
      #         image: [innovays/hello-app]
      #         path: [hello_app]
      #         docker-context: [hello_app]
      #         deploy: [true]
      #         # We publish two images with different version tags: 
      #         # - numbered version
      #         # - "latest"
      #         # tag: ['$(<hello_app/VERSION.txt)-${CIRCLE_SHA1:0:7}', 'latest']
      #         tag: ['$(<hello_app/VERSION.txt)', '1.000']
      #         update-description: [true]    
      #     requires: [init]
